import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Primary — sage green
        "primary-fixed-dim": "#a8d4b0",
        "on-error-container": "#6e0523",
        "surface-variant": "#e0d6bc",
        "on-secondary-fixed": "#1a3d25",
        "surface-container-highest": "#e0d6bc",
        "primary-container": "#c2e3c8",
        "tertiary-dim": "#7a6a40",
        "on-surface-variant": "#6b5e4d",
        "on-secondary-container": "#2a4d32",
        "secondary-container": "#d4e8c8",
        surface: "#fdf8ef",
        "error-container": "#f97386",
        "on-surface": "#332b1f",
        outline: "#9a8b7a",
        "inverse-on-surface": "#a09070",
        "surface-container-lowest": "#ffffff",
        error: "#a8364b",
        "on-error": "#fff7f7",
        "secondary-fixed": "#d4e8c8",
        "inverse-primary": "#c2e3c8",
        "secondary-dim": "#386050",
        "secondary-fixed-dim": "#b8d8be",
        primary: "#4e7c5f",
        "surface-tint": "#4e7c5f",
        "surface-bright": "#fdf8ef",
        "tertiary-container": "#e8d8a8",
        "surface-container": "#efe7ce",
        "surface-container-high": "#e8dfc6",
        "surface-dim": "#dfd4b8",
        "on-tertiary-fixed-variant": "#4a3a20",
        "on-primary-container": "#1a3d25",
        "on-tertiary-container": "#5a4a25",
        "on-tertiary-fixed": "#3d2d15",
        "inverse-surface": "#1a150d",
        "on-secondary": "#eef8ea",
        "primary-fixed": "#c2e3c8",
        "primary-dim": "#3d6b4e",
        "on-primary": "#f4faf6",
        "on-secondary-fixed-variant": "#2d5a3d",
        background: "#fdf8ef",
        secondary: "#4a6b45",
        "surface-container-low": "#f5eed8",
        "on-background": "#332b1f",
        tertiary: "#8a7a50",
        "on-primary-fixed-variant": "#2d5a3d",
        "tertiary-fixed": "#e8d8a8",
        "outline-variant": "#c8baa8",
        "error-dim": "#6b0221",
        "tertiary-fixed-dim": "#dece90",
        "on-primary-fixed": "#0d2c1a",
        "on-tertiary": "#fdf8ee",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
