import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c8b1f0",
        "on-error-container": "#6e0523",
        "surface-variant": "#e7e0e6",
        "on-secondary-fixed": "#1c4825",
        "surface-container-highest": "#e7e0e6",
        "primary-container": "#d6beff",
        "tertiary-dim": "#0e5881",
        "on-surface-variant": "#625e63",
        "on-secondary-container": "#2f5b36",
        "secondary-container": "#bdefbe",
        surface: "#fef8fb",
        "error-container": "#f97386",
        "on-surface": "#353136",
        outline: "#7e797e",
        "inverse-on-surface": "#a09c9e",
        "surface-container-lowest": "#ffffff",
        error: "#a8364b",
        "on-error": "#fff7f7",
        "secondary-fixed": "#bdefbe",
        "inverse-primary": "#d6beff",
        "secondary-dim": "#315c37",
        "secondary-fixed-dim": "#afe1b1",
        primary: "#69558e",
        "surface-tint": "#69558e",
        "surface-bright": "#fef8fb",
        "tertiary-container": "#95cfff",
        "surface-container": "#f3ecf1",
        "surface-container-high": "#ede6eb",
        "surface-dim": "#dfd8de",
        "on-tertiary-fixed-variant": "#005077",
        "on-primary-container": "#4b386e",
        "on-tertiary-container": "#00466a",
        "on-tertiary-fixed": "#00314c",
        "inverse-surface": "#0f0e10",
        "on-secondary": "#e9ffe6",
        "primary-fixed": "#d6beff",
        "primary-dim": "#5c4981",
        "on-primary": "#fef7ff",
        "on-secondary-fixed-variant": "#39653f",
        background: "#fef8fb",
        secondary: "#3c6942",
        "surface-container-low": "#f8f2f6",
        "on-background": "#353136",
        tertiary: "#22648e",
        "on-primary-fixed-variant": "#544178",
        "tertiary-fixed": "#95cfff",
        "outline-variant": "#b6b0b6",
        "error-dim": "#6b0221",
        "tertiary-fixed-dim": "#88c2f0",
        "on-primary-fixed": "#362459",
        "on-tertiary": "#f6f9ff",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
